// Package shim provides functionality for generating the vcluster shim script
// and shell initialization code.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateShimScript creates the vcluster shim script at $VCENV_ROOT/shims/vcluster.
// The shim resolves the correct vcluster version and executes it.
func GenerateShimScript(vcenvRoot string) error {
	shimsDir := filepath.Join(vcenvRoot, "shims")
	if err := os.MkdirAll(shimsDir, 0o755); err != nil {
		return fmt.Errorf("failed to create shims directory: %w", err)
	}

	shimPath := filepath.Join(shimsDir, "vcluster")
	shimContent := fmt.Sprintf(`#!/bin/sh
# This shim is generated by vc-env. Do not edit manually.
set -e

VCENV_ROOT="%s"

# Resolve version: VCENV_VERSION > .vcluster-version (walk up) > $VCENV_ROOT/version
resolve_version() {
    # 1. Check VCENV_VERSION env var (shell version)
    if [ -n "$VCENV_VERSION" ]; then
        echo "$VCENV_VERSION"
        return
    fi

    # 2. Walk up directories looking for .vcluster-version (local version)
    local dir="$PWD"
    while true; do
        if [ -f "$dir/.vcluster-version" ]; then
            cat "$dir/.vcluster-version"
            return
        fi
        local parent
        parent="$(dirname "$dir")"
        if [ "$parent" = "$dir" ]; then
            break
        fi
        dir="$parent"
    done

    # 3. Check global version
    if [ -f "$VCENV_ROOT/version" ]; then
        cat "$VCENV_ROOT/version"
        return
    fi

    echo "vc-env: no vcluster version configured" >&2
    echo "Set a version using 'vc-env shell', 'vc-env local', or 'vc-env global'" >&2
    exit 1
}

VERSION="$(resolve_version)"
BINARY="$VCENV_ROOT/versions/$VERSION/vcluster"

if [ ! -x "$BINARY" ]; then
    echo "vc-env: version $VERSION is not installed" >&2
    echo "Install it with: vc-env install $VERSION" >&2
    exit 1
fi

exec "$BINARY" "$@"
`, vcenvRoot)

	if err := os.WriteFile(shimPath, []byte(shimContent), 0o755); err != nil {
		return fmt.Errorf("failed to write shim script: %w", err)
	}

	return nil
}

// GenerateShellInit returns the shell initialization code that should be
// eval'd in the user's shell (e.g., eval "$(vc-env init)").
// It creates a shell function that intercepts the 'shell' subcommand to
// set/unset VCENV_VERSION in the current shell, and prepends the shims
// directory to PATH.
func GenerateShellInit(vcenvRoot string) string {
	return fmt.Sprintf(`export PATH="%s/shims:$PATH"

vc-env() {
  if [ "$1" = "shell" ]; then
    if [ -n "$2" ]; then
      # Validate via the real binary first
      command vc-env shell "$2" || return $?
      export VCENV_VERSION="$2"
    elif [ "$1" = "shell" ] && [ $# -eq 1 ]; then
      command vc-env shell
    fi
  else
    command vc-env "$@"
  fi
}
`, vcenvRoot)
}
